# permissions for end users to view hibernators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hibernator-viewer-role
rules:
- apiGroups:
  - pincher.devtron.ai
  resources:
  - hibernators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pincher.devtron.ai
  resources:
  - hibernators/status
  verbs:
  - get
